name: icofont_flutter
description: The IcoFont Icon Pack available as Flutter Icon Page
version: 1.0.0
author: Priyo Mukul <me@mukul.me>
homepage: https://github.com/priyomukul/icofont_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
   fonts:
     - family: IcoFont
       fonts:
         - asset: lib/fonts/icofont.ttf
